# 候选受限策略：真实内核及 mount/flush/unmount/拒绝测试通过后才能生产启用。
# 自包含；所有可信子进程只继承当前策略，不允许切换为 unconfined。
profile __SANDBOX_PROFILE_NAME__ flags=(attach_disconnected,mediate_deleted) {
  /usr/local/bin/workspace-mounter rix,
  /usr/bin/{s3fs,fusermount3,ls,cat,sync} rix,
  /bin/{ls,cat,sync} rix,
  /lib/** mr,
  /lib64/** mr,
  /usr/lib/** mr,
  /etc/ld.so.cache r,
  /etc/ld.so.preload r,
  /etc/{hosts,resolv.conf,nsswitch.conf,passwd,group,gai.conf,fuse.conf} r,
  /etc/ssl/** r,
  /etc/workspace-fuse/** r,
  /run/secrets/workspace/** r,
  /proc/ r,
  /proc/[0-9]*/{attr/current,mountinfo,status,stat,cmdline,maps} r,
  /proc/self/{attr/current,mountinfo,status,stat,cmdline,maps} r,
  /proc/sys/kernel/{ngroups_max,pid_max} r,
  /dev/fuse rw,
  /dev/null rw,
  /dev/urandom r,
  /dev/random r,
  /workspace rw,
  /workspace/ rw,
  /workspace/** rwkl,
  /var/cache/s3fs/ rw,
  /var/cache/s3fs/** rwkl,
  /run/s3fs/ rw,
  /run/s3fs/** rwkl,
  capability sys_admin,
  capability dac_override,
  capability dac_read_search,
  capability chown,
  capability fowner,
  capability fsetid,
  capability setuid,
  capability setgid,
  network inet stream,
  network inet6 stream,
  network inet dgram,
  network inet6 dgram,
  network unix stream,
  signal (send, receive) peer=sandbox-fuse-*,
  signal (receive) peer=unconfined,
  ptrace (read) peer=sandbox-fuse-*,
  mount fstype=fuse.s3fs -> /workspace/,
  umount /workspace/,
}
